---
apiVersion: self-node-remediation.medik8s.io/v1alpha1
kind: SelfNodeRemediationTemplate
metadata:
  name: self-node-remediation-node-template
  namespace: openshift-workload-availability
spec:
  template:
    spec:
      remediationStrategy: Automatic
