---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./acm/
  # - ./cluster-observability/
  - ./data-foundation/
  - ./metallb/
  - ./nmstate/
  # - ./openshift-gitops/
  - ./openshift-virtualization/
  - ./workload-availability-operators/
  - ./service-mesh
