---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./acm-configs/
  - ./acm-placements/
  - ./cluster-configs/
  - ./cluster-validations/
   # - ./cluster-maintenance/
  - ./operators/
  - ./cluster-version/
  - ./cluster-health/
